"""coach message images

Revision ID: 4b332e3cb403
Revises: 9d2c41b7a6e3
Create Date: 2026-10-08 18:44:38.935716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b332e3cb403'
down_revision: Union[str, Sequence[str], None] = '9d2c41b7a6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_mime', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_message', schema=None) as batch_op:
        batch_op.drop_column('image_data')
        batch_op.drop_column('image_mime')

    # ### end Alembic commands ###
