"""baseline: rider_profile

Revision ID: bd67396e9db5
Revises:
Create Date: 2026-09-16 21:33:26.745119

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd67396e9db5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("sport", sa.String(length=64), nullable=False),
        sa.Column("sub_sport", sa.String(length=64), nullable=False),
        sa.Column("is_indoor", sa.Boolean(), nullable=False),
        sa.Column("bike_type", sa.String(length=16), nullable=False),
        sa.Column("distance_m", sa.Float(), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=False),
        sa.Column("elev_gain_m", sa.Float(), nullable=False),
        sa.Column("avg_hr", sa.Integer(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("avg_power_w", sa.Integer(), nullable=True),
        sa.Column("max_power_w", sa.Integer(), nullable=True),
        sa.Column("avg_cadence", sa.Integer(), nullable=True),
        sa.Column("has_power_data", sa.Boolean(), nullable=False),
        sa.Column("has_hr_data", sa.Boolean(), nullable=False),
        sa.Column("has_cadence_data", sa.Boolean(), nullable=False),
        sa.Column("has_speed_data", sa.Boolean(), nullable=False),
        sa.Column("has_gps_data", sa.Boolean(), nullable=False),
        sa.Column("fit_status", sa.String(length=16), nullable=False),
        sa.Column("fit_path", sa.String(), nullable=True),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("records_stored", sa.Boolean(), nullable=False),
        sa.Column("raw_summary_json", sa.JSON(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "garmin_sync_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_seen_activity_id", sa.Integer(), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column("last_status", sa.String(length=16), nullable=False),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.Column("consecutive_errors", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rider_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("weekly_rides", sa.Integer(), nullable=False),
        sa.Column("weekly_hours", sa.Float(), nullable=False),
        sa.Column("primary_discipline", sa.String(length=16), nullable=False),
        sa.Column("goal_text", sa.String(), nullable=False),
        sa.Column("target_event_date", sa.Date(), nullable=True),
        sa.Column("has_power_meter", sa.Boolean(), nullable=False),
        sa.Column("has_hr_monitor", sa.Boolean(), nullable=False),
        sa.Column("has_cadence_sensor", sa.Boolean(), nullable=False),
        sa.Column("has_speed_sensor", sa.Boolean(), nullable=False),
        sa.Column("ftp_watts", sa.Integer(), nullable=True),
        sa.Column("lthr", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lap",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("lap_index", sa.Integer(), nullable=False),
        sa.Column("distance_m", sa.Float(), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=False),
        sa.Column("avg_hr", sa.Integer(), nullable=True),
        sa.Column("avg_speed_mps", sa.Float(), nullable=True),
        sa.Column("avg_power_w", sa.Integer(), nullable=True),
        sa.Column("avg_cadence", sa.Integer(), nullable=True),
        sa.Column("elev_gain_m", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["activity_id"], ["activity.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("activity_id", "lap_index"),
    )
    op.create_table(
        "record",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("t_offset_s", sa.Float(), nullable=False),
        sa.Column("hr", sa.Integer(), nullable=True),
        sa.Column("speed_mps", sa.Float(), nullable=True),
        sa.Column("altitude_m", sa.Float(), nullable=True),
        sa.Column("cadence", sa.Integer(), nullable=True),
        sa.Column("power_w", sa.Integer(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["activity_id"], ["activity.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("record", schema=None) as batch_op:
        batch_op.create_index("ix_record_activity_t", ["activity_id", "t_offset_s"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("record", schema=None) as batch_op:
        batch_op.drop_index("ix_record_activity_t")

    op.drop_table("record")
    op.drop_table("lap")
    op.drop_table("rider_profile")
    op.drop_table("garmin_sync_state")
    op.drop_table("activity")
    # ### end Alembic commands ###
