"""rider garage

Revision ID: efb567af688f
Revises: cfd4848eaf23
Create Date: 2026-09-21 20:36:32.342870

Adds the `bike` table and the new coach-intake fields on `rider_profile`
(exec-plan 0004). Between the two `rider_profile` batch blocks below,
`upgrade()` seeds exactly one `bike` row from the existing profile row's
`primary_discipline`/`has_power_meter`/`has_cadence_sensor`/
`has_speed_sensor` — hand-written, not autogenerated — so an existing
single-bike rider keeps their declared sensors instead of landing in an
empty garage. A fresh database (no `rider_profile` row yet) seeds
nothing; onboarding's GarageStep handles that case.
"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efb567af688f"
down_revision: str | Sequence[str] | None = "cfd4848eaf23"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "bike",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nickname", sa.String(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("has_power_meter", sa.Boolean(), nullable=False),
        sa.Column("has_cadence_sensor", sa.Boolean(), nullable=False),
        sa.Column("has_speed_sensor", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # Add the new columns first — the two JSON list columns get a
    # temporary server_default so SQLite can backfill NOT NULL onto any
    # existing row; dropped again below once the seed step has run,
    # so future rows rely on the ORM-level `default=list` instead.
    with op.batch_alter_table("rider_profile", schema=None) as batch_op:
        batch_op.add_column(sa.Column("target_event_name", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("focus_areas", sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )
        batch_op.add_column(sa.Column("years_riding", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("longest_recent_ride_km", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("followed_plan_before", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("self_rated_level", sa.String(length=16), nullable=True))
        batch_op.add_column(
            sa.Column("available_days", sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )
        batch_op.add_column(sa.Column("weekday_max_minutes", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("weekend_max_minutes", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("birth_year", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("weight_kg", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("max_hr", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("health_notes", sa.String(), nullable=True))

    # Seed one bike from the row being retired below, while its old
    # columns are still readable (plain SQL — the ORM models describe the
    # *new* schema, not this transitional one).
    bind = op.get_bind()
    row = bind.execute(
        sa.text(
            "SELECT primary_discipline, has_power_meter, has_cadence_sensor, has_speed_sensor "
            "FROM rider_profile WHERE id = 1"
        )
    ).fetchone()
    if row is not None:
        discipline, has_power_meter, has_cadence_sensor, has_speed_sensor = row
        # isoformat string, not a raw datetime object — sqlite3's implicit
        # datetime adapter is deprecated as of Python 3.12.
        now = datetime.now(UTC).replace(tzinfo=None).isoformat(sep=" ")
        bind.execute(
            sa.text(
                "INSERT INTO bike "
                "(nickname, kind, is_primary, has_power_meter, has_cadence_sensor, "
                " has_speed_sensor, created_at, updated_at) "
                "VALUES (:nickname, :kind, 1, :has_power_meter, :has_cadence_sensor, "
                " :has_speed_sensor, :now, :now)"
            ),
            {
                "nickname": "My bike",
                "kind": discipline or "road",
                "has_power_meter": bool(has_power_meter),
                "has_cadence_sensor": bool(has_cadence_sensor),
                "has_speed_sensor": bool(has_speed_sensor),
                "now": now,
            },
        )

    with op.batch_alter_table("rider_profile", schema=None) as batch_op:
        batch_op.drop_column("has_power_meter")
        batch_op.drop_column("has_speed_sensor")
        batch_op.drop_column("primary_discipline")
        batch_op.drop_column("has_cadence_sensor")
        batch_op.alter_column("focus_areas", server_default=None)
        batch_op.alter_column("available_days", server_default=None)


def downgrade() -> None:
    """Downgrade schema.

    Does not attempt to reconstruct rider_profile's old sensor columns
    from the bike(s) that may exist by then — a garage can hold more than
    one bike, so there is no single unambiguous bike to collapse back
    down to. The dropped columns come back with their old defaults only.
    """
    with op.batch_alter_table("rider_profile", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "has_cadence_sensor", sa.BOOLEAN(), nullable=False, server_default=sa.text("0")
            )
        )
        batch_op.add_column(
            sa.Column(
                "primary_discipline", sa.VARCHAR(length=16), nullable=False, server_default="road"
            )
        )
        batch_op.add_column(
            sa.Column("has_speed_sensor", sa.BOOLEAN(), nullable=False, server_default=sa.text("0"))
        )
        batch_op.add_column(
            sa.Column("has_power_meter", sa.BOOLEAN(), nullable=False, server_default=sa.text("0"))
        )
        batch_op.alter_column("has_cadence_sensor", server_default=None)
        batch_op.alter_column("primary_discipline", server_default=None)
        batch_op.alter_column("has_speed_sensor", server_default=None)
        batch_op.alter_column("has_power_meter", server_default=None)
        batch_op.drop_column("health_notes")
        batch_op.drop_column("max_hr")
        batch_op.drop_column("weight_kg")
        batch_op.drop_column("birth_year")
        batch_op.drop_column("weekend_max_minutes")
        batch_op.drop_column("weekday_max_minutes")
        batch_op.drop_column("available_days")
        batch_op.drop_column("self_rated_level")
        batch_op.drop_column("followed_plan_before")
        batch_op.drop_column("longest_recent_ride_km")
        batch_op.drop_column("years_riding")
        batch_op.drop_column("focus_areas")
        batch_op.drop_column("target_event_name")

    op.drop_table("bike")
