"""phase1_initial_schema

Revision ID: 9a7cef0bbfd8
Revises:
Create Date: 2026-05-11 21:47:17.262360

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a7cef0bbfd8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sport", sa.String(length=64), nullable=False),
        sa.Column("sub_sport", sa.String(length=64), nullable=False),
        sa.Column("is_indoor", sa.Boolean(), nullable=False),
        sa.Column("bike_type", sa.String(length=16), nullable=False),
        sa.Column("distance_m", sa.Float(), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=False),
        sa.Column("elev_gain_m", sa.Float(), nullable=False),
        sa.Column("avg_hr", sa.Integer(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("tss_proxy", sa.Float(), nullable=True),
        sa.Column("fit_path", sa.Text(), nullable=True),
        sa.Column("raw_summary_json", sa.JSON(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "garth_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("encrypted_blob", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "poll_cursor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_seen_activity_id", sa.Integer(), nullable=True),
        sa.Column("last_poll_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_poll_status", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wellness_daily",
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("hrv_overnight", sa.Float(), nullable=True),
        sa.Column("sleep_score", sa.Integer(), nullable=True),
        sa.Column("body_battery_low", sa.Integer(), nullable=True),
        sa.Column("body_battery_high", sa.Integer(), nullable=True),
        sa.Column("resting_hr", sa.Integer(), nullable=True),
        sa.Column("acute_load", sa.Float(), nullable=True),
        sa.Column("chronic_load", sa.Float(), nullable=True),
        sa.Column("acwr", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("date"),
    )
    op.create_table(
        "lap",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("lap_index", sa.Integer(), nullable=False),
        sa.Column("distance_m", sa.Float(), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=False),
        sa.Column("avg_hr", sa.Integer(), nullable=True),
        sa.Column("avg_speed", sa.Float(), nullable=True),
        sa.Column("elev_gain_m", sa.Float(), nullable=False),
        sa.Column("gap_speed", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["activity_id"], ["activity.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("activity_id", "lap_index"),
    )
    op.create_table(
        "metrics",
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("decoupling_pct", sa.Float(), nullable=True),
        sa.Column("hr_drift_pct", sa.Float(), nullable=True),
        sa.Column("time_in_z1", sa.Float(), nullable=True),
        sa.Column("time_in_z2", sa.Float(), nullable=True),
        sa.Column("time_in_z3", sa.Float(), nullable=True),
        sa.Column("time_in_z4", sa.Float(), nullable=True),
        sa.Column("time_in_z5", sa.Float(), nullable=True),
        sa.Column("vam_best_20min", sa.Float(), nullable=True),
        sa.Column("gap_normalized", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["activity_id"], ["activity.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("activity_id"),
    )
    op.create_table(
        "record",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("t_offset_s", sa.Float(), nullable=False),
        sa.Column("hr", sa.Integer(), nullable=True),
        sa.Column("speed_mps", sa.Float(), nullable=True),
        sa.Column("altitude_m", sa.Float(), nullable=True),
        sa.Column("cadence", sa.Integer(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["activity_id"], ["activity.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("record")
    op.drop_table("metrics")
    op.drop_table("lap")
    op.drop_table("wellness_daily")
    op.drop_table("poll_cursor")
    op.drop_table("garth_token")
    op.drop_table("activity")
    # ### end Alembic commands ###
