#!/usr/bin/env python3
"""Regenerate docs/generated/db-schema.md from SQLAlchemy metadata.

Run via `make docs-schema`. Do not hand-edit the output file.
"""

from __future__ import annotations

from pathlib import Path

from soft_floyd_core.models import Base

OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "generated" / "db-schema.md"


def render() -> str:
    lines = ["# Database Schema", "", "Generated by `make docs-schema`. Do not hand-edit.", ""]
    for table in Base.metadata.sorted_tables:
        lines.append(f"## `{table.name}`")
        lines.append("")
        lines.append("| Column | Type | Nullable | Default |")
        lines.append("|---|---|---|---|")
        for column in table.columns:
            default = ""
            if column.default is not None:
                arg = column.default.arg
                default = "(computed)" if callable(arg) else arg
            lines.append(f"| {column.name} | {column.type} | {column.nullable} | {default} |")
        lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render())
    print(f"Wrote {OUTPUT}")
